# Generated by Django 3.2.5 on 2021-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='NACCS_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
